/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DriverProfile {
  'vehicleType' : string,
  'name' : string,
  'isOnline' : boolean,
  'rating' : number,
  'phoneNumber' : string,
  'totalRides' : bigint,
}
export interface EarningsSummary {
  'weeklyEarnings' : Array<number>,
  'totalTrips' : bigint,
  'todayEarnings' : number,
}
export interface Location { 'area' : string, 'city' : string }
export interface Notification { 'message' : string, 'timestamp' : Time }
export interface RideRequest {
  'driverId' : Principal,
  'isAccepted' : boolean,
  'distance' : number,
  'passengerName' : string,
  'fareAmount' : number,
  'dropLocation' : Location,
  'requestTime' : Time,
  'pickupLocation' : Location,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRide' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTrip' : ActorMethod<[bigint], undefined>,
  'completeTrip' : ActorMethod<[bigint], undefined>,
  'createProfile' : ActorMethod<[string, string, string], undefined>,
  'createRideRequest' : ActorMethod<
    [Location, Location, number, string, number, Principal],
    bigint
  >,
  'createRideRequestAsAdmin' : ActorMethod<
    [Location, Location, number, string, number, Principal],
    bigint
  >,
  'getAllDrivers' : ActorMethod<[], Array<[Principal, DriverProfile]>>,
  'getAllRideRequests' : ActorMethod<[], Array<[bigint, RideRequest]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [DriverProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEarnings' : ActorMethod<[], EarningsSummary>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingRideRequests' : ActorMethod<[], Array<RideRequest>>,
  'getProfile' : ActorMethod<[], [] | [DriverProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [DriverProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[DriverProfile], undefined>,
  'sendNotification' : ActorMethod<[Principal, string], undefined>,
  'updateOnlineStatus' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];