/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({ 'area' : IDL.Text, 'city' : IDL.Text });
export const DriverProfile = IDL.Record({
  'vehicleType' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'rating' : IDL.Float64,
  'phoneNumber' : IDL.Text,
  'totalRides' : IDL.Nat,
});
export const Time = IDL.Int;
export const RideRequest = IDL.Record({
  'driverId' : IDL.Principal,
  'isAccepted' : IDL.Bool,
  'distance' : IDL.Float64,
  'passengerName' : IDL.Text,
  'fareAmount' : IDL.Float64,
  'dropLocation' : Location,
  'requestTime' : Time,
  'pickupLocation' : Location,
});
export const EarningsSummary = IDL.Record({
  'weeklyEarnings' : IDL.Vec(IDL.Float64),
  'totalTrips' : IDL.Nat,
  'todayEarnings' : IDL.Float64,
});
export const Notification = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRide' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTrip' : IDL.Func([IDL.Nat], [], []),
  'completeTrip' : IDL.Func([IDL.Nat], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createRideRequest' : IDL.Func(
      [Location, Location, IDL.Float64, IDL.Text, IDL.Float64, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'createRideRequestAsAdmin' : IDL.Func(
      [Location, Location, IDL.Float64, IDL.Text, IDL.Float64, IDL.Principal],
      [IDL.Nat],
      [],
    ),
  'getAllDrivers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, DriverProfile))],
      ['query'],
    ),
  'getAllRideRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, RideRequest))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarnings' : IDL.Func([], [EarningsSummary], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingRideRequests' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DriverProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([DriverProfile], [], []),
  'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({ 'area' : IDL.Text, 'city' : IDL.Text });
  const DriverProfile = IDL.Record({
    'vehicleType' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'rating' : IDL.Float64,
    'phoneNumber' : IDL.Text,
    'totalRides' : IDL.Nat,
  });
  const Time = IDL.Int;
  const RideRequest = IDL.Record({
    'driverId' : IDL.Principal,
    'isAccepted' : IDL.Bool,
    'distance' : IDL.Float64,
    'passengerName' : IDL.Text,
    'fareAmount' : IDL.Float64,
    'dropLocation' : Location,
    'requestTime' : Time,
    'pickupLocation' : Location,
  });
  const EarningsSummary = IDL.Record({
    'weeklyEarnings' : IDL.Vec(IDL.Float64),
    'totalTrips' : IDL.Nat,
    'todayEarnings' : IDL.Float64,
  });
  const Notification = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRide' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTrip' : IDL.Func([IDL.Nat], [], []),
    'completeTrip' : IDL.Func([IDL.Nat], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createRideRequest' : IDL.Func(
        [Location, Location, IDL.Float64, IDL.Text, IDL.Float64, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'createRideRequestAsAdmin' : IDL.Func(
        [Location, Location, IDL.Float64, IDL.Text, IDL.Float64, IDL.Principal],
        [IDL.Nat],
        [],
      ),
    'getAllDrivers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, DriverProfile))],
        ['query'],
      ),
    'getAllRideRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, RideRequest))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarnings' : IDL.Func([], [EarningsSummary], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingRideRequests' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([DriverProfile], [], []),
    'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };